// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: sanctify-api.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname  string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	WsPort    int32  `protobuf:"varint,2,opt,name=ws_port,json=wsPort,proto3" json:"ws_port,omitempty"`
	GameToken string `protobuf:"bytes,3,opt,name=game_token,json=gameToken,proto3" json:"game_token,omitempty"`
}

func (x *GameServer) Reset() {
	*x = GameServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sanctify_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServer) ProtoMessage() {}

func (x *GameServer) ProtoReflect() protoreflect.Message {
	mi := &file_sanctify_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServer.ProtoReflect.Descriptor instead.
func (*GameServer) Descriptor() ([]byte, []int) {
	return file_sanctify_api_proto_rawDescGZIP(), []int{0}
}

func (x *GameServer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GameServer) GetWsPort() int32 {
	if x != nil {
		return x.WsPort
	}
	return 0
}

func (x *GameServer) GetGameToken() string {
	if x != nil {
		return x.GameToken
	}
	return ""
}

type GetGameServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServer *GameServer `protobuf:"bytes,1,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
}

func (x *GetGameServerResponse) Reset() {
	*x = GetGameServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sanctify_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameServerResponse) ProtoMessage() {}

func (x *GetGameServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sanctify_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameServerResponse.ProtoReflect.Descriptor instead.
func (*GetGameServerResponse) Descriptor() ([]byte, []int) {
	return file_sanctify_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameServerResponse) GetGameServer() *GameServer {
	if x != nil {
		return x.GameServer
	}
	return nil
}

type GetGameServerError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GetGameServerError) Reset() {
	*x = GetGameServerError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sanctify_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameServerError) ProtoMessage() {}

func (x *GetGameServerError) ProtoReflect() protoreflect.Message {
	mi := &file_sanctify_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameServerError.ProtoReflect.Descriptor instead.
func (*GetGameServerError) Descriptor() ([]byte, []int) {
	return file_sanctify_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameServerError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_sanctify_api_proto protoreflect.FileDescriptor

var file_sanctify_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x61, 0x6e, 0x63, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x61, 0x6e, 0x63, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70,
	0x62, 0x22, 0x60, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x77,
	0x73, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x73,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x51, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x73, 0x61, 0x6e, 0x63, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x65, 0x73, 0x73, 0x61, 0x6d, 0x65, 0x6b, 0x65, 0x73, 0x68, 0x2f, 0x73, 0x61, 0x6e, 0x63,
	0x74, 0x69, 0x66, 0x79, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x61, 0x6e,
	0x63, 0x74, 0x69, 0x66, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sanctify_api_proto_rawDescOnce sync.Once
	file_sanctify_api_proto_rawDescData = file_sanctify_api_proto_rawDesc
)

func file_sanctify_api_proto_rawDescGZIP() []byte {
	file_sanctify_api_proto_rawDescOnce.Do(func() {
		file_sanctify_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_sanctify_api_proto_rawDescData)
	})
	return file_sanctify_api_proto_rawDescData
}

var file_sanctify_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sanctify_api_proto_goTypes = []interface{}{
	(*GameServer)(nil),            // 0: sanctify.pb.GameServer
	(*GetGameServerResponse)(nil), // 1: sanctify.pb.GetGameServerResponse
	(*GetGameServerError)(nil),    // 2: sanctify.pb.GetGameServerError
}
var file_sanctify_api_proto_depIdxs = []int32{
	0, // 0: sanctify.pb.GetGameServerResponse.game_server:type_name -> sanctify.pb.GameServer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sanctify_api_proto_init() }
func file_sanctify_api_proto_init() {
	if File_sanctify_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sanctify_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sanctify_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sanctify_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameServerError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sanctify_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sanctify_api_proto_goTypes,
		DependencyIndexes: file_sanctify_api_proto_depIdxs,
		MessageInfos:      file_sanctify_api_proto_msgTypes,
	}.Build()
	File_sanctify_api_proto = out.File
	file_sanctify_api_proto_rawDesc = nil
	file_sanctify_api_proto_goTypes = nil
	file_sanctify_api_proto_depIdxs = nil
}
