#ifndef SANCTIFY_GAME_COMMON_INCLUDE_SANCTIFY_GAME_COMMON_NET_NET_CONFIG_H
#define SANCTIFY_GAME_COMMON_INCLUDE_SANCTIFY_GAME_COMMON_NET_NET_CONFIG_H

namespace sanctify {

const int kSanctifyMagicHeader = 0xBEEFF00D;

}

#endif
